### ISSUE TITLE
Break example app tests into unit and request tests

### ISSUE THREAD

**Issue by blaix** [blaix/woma#5]
Right now the tests are serving as woma's acceptance tests. Call those request tests and then add unit tests to serve as an example of how a woma project could be TDD'd

**Comment by blaix** [comment]
I would like to use [tdubs](https://github.com/blaix/tdubs) for this. Waiting on first release.

**Comment by thomasw** [comment]
@blaix: tdubs has been released. Why isn't this done yet?

**Comment by blaix** [comment]
@thomasw you happy now?

**Comment by thomasw** [comment]
I'm thrilled!
